drop table cargo;
CREATE TABLE
CARGO 
(
ID				NUMBER(20) NOT NULL,
NOME            VARCHAR2(150) NOT NULL,
DESCRICAO       VARCHAR2(300),
NIVEL           NUMBER(20) NOT NULL,
VALOR_BASE_HORA NUMBER(20,2) NOT NULL,
CONSTRAINT PK_CARGO_01 PRIMARY KEY(ID)
)
;
TRUNCATE TABLE CONTA_BANCARIA;
DROP TABLE CONTA_BANCARIA;
CREATE TABLE
CONTA_BANCARIA
(
ID        NUMBER(20) NOT NULL,
BANCO     NUMBER(20) NOT NULL,
AGENCIA   NUMBER(20) NOT NULL,
CONTA     NUMBER(20) NOT NULL,
TIPO      NUMBER(20) NOT NULL,
CONSTRAINT PK_CONTA_BANCARIA_01 PRIMARY KEY (ID)
);

DROP TABLE ENDERECO;
CREATE TABLE
ENDERECO
(
ID			NUMBER(20)	  NOT NULL,
RUA         VARCHAR2(150) NOT NULL,
NUMERO      NUMBER(20)    NOT NULL,
CEP         NUMBER(20)    NOT NULL,
ESTADO      VARCHAR2(50)   ,
PAIS        VARCHAR2(50)   ,
CONSTRAINT PK_ENDERECO_01 PRIMARY KEY (ID)
);

DROP TABLE COLABORADOR;

CREATE TABLE
COLABORADOR
(
ID             NUMBER(20) NOT NULL,
NOME           VARCHAR2(150) NOT NULL,
CPF            NUMBER (11) NOT NULL,
DT_NASCIMENTO  DATE,
GENERO         VARCHAR2(1),
EMAIL          VARCHAR2(150),
CTPS_NUM       NUMBER(11) NOT NULL,
PIS_PASEP      NUMBER(11) NOT NULL,
ID_CONTA_BANCARIA  NUMBER(20) NOT NULL,
ID_ENDERECO    NUMBER(20),
ID_CARGO       NUMBER(20) NOT NULL,
 CONSTRAINT PK_COLABORADOR_01 PRIMARY KEY (ID),
 CONSTRAINT C_COLABORADOR_02 UNIQUE (CPF,CTPS_NUM,PIS_PASEP),
 CONSTRAINT FK_COLABORADOR_01 FOREIGN KEY (ID_ENDERECO)  REFERENCES ENDERECO (ID),
 CONSTRAINT FK_COLABORADOR_02 FOREIGN KEY (ID_CONTA_BANCARIA)  REFERENCES CONTA_BANCARIA (ID),
 CONSTRAINT FK_COLABORADOR_03 FOREIGN KEY (ID_CARGO)  REFERENCES CARGO (ID)
);

DROP TABLE TELEFONE;
CREATE TABLE
TELEFONE 
(
ID			NUMBER(20)  NOT NULL,
ID_COLABORADOR NUMBER(20)  NOT NULL,
PREFIXO     NUMBER(20)  NOT NULL,
NUMERO      NUMBER(20)  NOT NULL,
TIPO        NUMBER(20)  NOT NULL,
CONSTRAINT PK_TELEFONE_01 PRIMARY KEY (ID,ID_COLABORADOR),
CONSTRAINT FK_TELEFONE_01 FOREIGN KEY (ID_COLABORADOR)  REFERENCES COLABORADOR (ID)
);

CREATE SEQUENCE SEQ_COLABORADOR
 START WITH     1000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 CREATE SEQUENCE SEQ_CONTA_BANCARIA
 START WITH     1000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 CREATE SEQUENCE SEQ_CARGO
 START WITH     1000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 CREATE SEQUENCE SEQ_ENDERECO
 START WITH     1000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
  CREATE SEQUENCE SEQ_TELEFONE
 START WITH     1000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
   CREATE SEQUENCE SEQ_COL_TELEFONE
 START WITH     1000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 
 
DROP TRIGGER TRG_TELEFONE_01;
CREATE TRIGGER TRG_TELEFONE_01 AFTER INSERT ON COLABORADOR
BEGIN
    INSERT INTO TELEFONE (ID, ID_COLABORADOR,PREFIXO,NUMERO,TIPO) VALUES ((SELECT SEQ_TELEFONE.NEXTVAL FROM DUAL),NEW.ID,00,11111111,1);
END;
/