INSERT INTO COLABORADOR (
ID, 
NOME, 
CPF, 
DT_NASCIMENTO, 
GENERO, 
EMAIL, 
CTPS_NUM, 
PIS_PASEP, 
ID_CONTA_BANCARIA, 
ID_TELEFONE, 
ID_ENDERECO, 
ID_CARGO) 
VALUES (?,?,?,?,?,?,?,?,?,?,?,?);