INSERT INTO CARGO (ID,NOME,DESCRICAO,NIVEL,VALOR_BASE_HORA) VALUES (SEQ_CARGO.NEXTVAL,'ANALISTA DE SISTEMAS','ATUA EM PROJETOS, MANUTENCAO, MELHORIAS DE SISTEMAS DA EMPRESA',1,11.66);
INSERT INTO CARGO (ID,NOME,DESCRICAO,NIVEL,VALOR_BASE_HORA) VALUES (0,'ERRO DE CARGO','CARGO GENERICO',1,1);
SELECT * FROM CARGO;

INSERT INTO CARGO (ID,NOME,DESCRICAO,NIVEL,VALOR_BASE_HORA) VALUES (SEQ_CARGO.NEXTVAL,?,?,?,?);

INSERT INTO CONTA_BANCARIA (ID,BANCO,AGENCIA,CONTA,TIPO) VALUES (SEQ_CONTA_BANCARIA.NEXTVAL,104,12321,3213,1);
INSERT INTO CONTA_BANCARIA (ID,BANCO,AGENCIA,CONTA,TIPO) VALUES (0,1,1,1,1);
SELECT * FROM CONTA_BANCARIA;

SELECT * FROM ENDERECO;
INSERT INTO ENDERECO (ID,RUA,NUMERO,CEP,ESTADO,PAIS) VALUES (SEQ_ENDERECO.NEXTVAL,'PEDRO ELIAS GRACIANO',164,83320510,'PARANA','BRASIL');
INSERT INTO ENDERECO (ID,RUA,NUMERO,CEP,ESTADO,PAIS) VALUES (0,'ENDERECO GENERICO',1,1,'GENERICO','GENERICO');


DELETE COLABORADOR;
INSERT INTO COLABORADOR (ID,NOME,CPF,CTPS_NUM,PIS_PASEP,ID_CONTA_BANCARIA,ID_ENDERECO, ID_CARGO) VALUES (SEQ_COLABORADOR.NEXTVAL,'DIEGO SERONATO',04391655985,12321,102938920,1001,1004,1005);
INSERT INTO COLABORADOR (ID,NOME,CPF,CTPS_NUM,PIS_PASEP,ID_CONTA_BANCARIA,ID_ENDERECO, ID_CARGO) VALUES (SEQ_COLABORADOR.NEXTVAL,'DIEGO SERONATO',04391655987,12321,102938920,1001,1004,1005);


SELECT * FROM COLABORADOR;
INSERT INTO COLABORADOR (ID, NOME, CPF, DT_NASCIMENTO, GENERO, EMAIL, CTPS_NUM, PIS_PASEP, ID_CONTA_BANCARIA, ID_TELEFONE, ID_ENDERECO, ID_CARGO) VALUES (?,?,?,?,?,?,?,?,?,?,?,?);

DELETE TELEFONE;
SELECT * FROM TELEFONE;
INSERT INTO TELEFONE (ID, ID_COLABORADOR,PREFIXO,NUMERO,TIPO) VALUES (SEQ_TELEFONE.NEXTVAL,1019,41,25252095,1);
INSERT INTO TELEFONE (ID, ID_COLABORADOR,PREFIXO,NUMERO,TIPO) VALUES (SEQ_TELEFONE.NEXTVAL,1025,41,25252095,1);



select SEQ_COLABORADOR.NEXTVAL from dual;

update colaborador
set dt_nascimento = to_date('30/03/1992'),
genero = 'M',
email = 'DIEGO.SERONATO@TELEFONICA.COM',
ID_ENDERECO = 1003;


COMMIT;



ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy HH24:MI:SS';

DROP MATERIALIZED VIEW DADOS_COLABORADORES;

CREATE MATERIALIZED VIEW DADOS_COLABORADORES 
   BUILD IMMEDIATE
   REFRESH FORCE NEXT  SYSDATE + 1/10000
AS
SELECT  CO.ID, CO.NOME, CO.CPF, CO.DT_NASCIMENTO, CO.GENERO, CO.EMAIL, CO.CTPS_NUM, CO.PIS_PASEP,
        CB.ID ID_CONTA, CB.BANCO, CB.AGENCIA, CB.CONTA,CB.TIPO,
        TE.ID ID_TELEFONE, TE.ID_COLABORADOR, TE.PREFIXO, TE.NUMERO, TE.TIPO TIPO_TELEFONE,
        E.ID ID_ENDERECO, E.RUA, E.NUMERO NUMERO_RUA, E.CEP, E.ESTADO, E.PAIS,
        CA.ID ID_CARGO, CA.NOME NOME_CARGO, CA.DESCRICAO, CA.NIVEL, CA.VALOR_BASE_HORA
FROM 
COLABORADOR CO JOIN CARGO CA
ON CO.ID_CARGO = CA.ID
JOIN TELEFONE TE
ON CO.ID = TE.ID_COLABORADOR
JOIN CONTA_BANCARIA CB
ON CO.ID_CONTA_BANCARIA = CB.ID
JOIN ENDERECO E
ON CO.ID_ENDERECO = E.ID;

DADOS_COLABORADORES;

SELECT * FROM DADOS_COLABORADORES;


UPDATE CARGO SET NOME=?, DESCRICAO=?, NIVEL =?, VALOR_BASE_HORA=? WHERE ID =?

